# Generated by Django 2.2 on 2019-03-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_auto_20190305_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='dateaccountcreate',
            new_name='dateaccountcreated',
        ),
    ]
