# Generated by Django 2.2 on 2019-03-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_auto_20190305_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_model',
            new_name='user_key',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='game_model',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameApp.UserModel'),
        ),
    ]
