# Generated by Django 2.2 on 2019-03-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_auto_20190305_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='delovper',
            new_name='developer',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ageLimit',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='rank',
        ),
    ]
