# Generated by Django 2.0.6 on 2019-03-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_auto_20190305_1753'),
        ('gameApp', '0005_auto_20190305_1929'),
    ]

    operations = [
    ]
